---
# Set up accounts and accesses

- name: change root password
  user: name=root password={{ root_password | password_hash('sha512') }}

- name: add admin user
  user:
    name: "{{ admin_username }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: add authorized keys for admin user
  authorized_key:
    user: "{{ admin_username }}"
    key: "{{ lookup('file', '{{ public_key }}') }}"

- name: create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: create sudoer file for admin
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ admin_username }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
