---
# Basic Apache setup

- name: ensure apache is installed
  yum: name=httpd state=present
      
- name: ensure apache is running and enabled
  service: name=httpd state=started enabled=yes
    
- name: enable firewalld http service
  firewalld: service=http permanent=true immediate=true state=enabled
      
- name: enable firewalld https service
  firewalld: service=https permanent=true immediate=true state=enabled
